[game]
sell_tile = [9, 4]
buy_tiles = [
    [-2, 4],
    [-2, 3],
    [-2, 2],
]

[graphics]
multisampling = 4
resolution = [1280, 720]
vsync = true

[colors]
black = [0.025, 0.025, 0.025, 1.0]
white = [0.9, 0.9, 0.9, 1.0]
grey = [0.09, 0.09, 0.09, 1.0]
sky = [0.4, 0.4, 0.8, 1.0]
cursor = [1.0, 1.0, 0.0, 0.75]
selected = [1.0, 1.0, 0.5, 0.75]
dest = [0.0, 1.0, 1.0, 0.75]
place = [1.0, 1.0, 0.0, 0.75]
forsale = [0.5, 0.5, 1.0, 1.0]

[text]
size = 64
viewport = [16.0, 9.0, 1.0, 1.0]

[text.turnlabel]
pos = [-0.4, 3.75, 0.0]
size = 24.0

[camera]
distance = 11.31371
angle = 0.0
tilt = 45.0
fov = 0.125

[light]
key_dir = [1.0, -3.5, 1.0, 0.0]
fill_dir = [-1.0, -3.5, 1.0, 0.0]
back_dir = [0.0, -1.0, -2.0, 0.0]
key_color = [0.8, 0.8, 0.8, 1.0]
fill_color = [0.4, 0.4, 0.4, 1.0]
back_color = [0.2, 0.2, 0.2, 1.0]
amb_color = [0.1, 0.1, 0.1, 1.0]
specular_power = 20.0
specular_color = [0.1, 0.1, 0.1]

[weights]
pawn = 22
knight = 18
rook = 16
bishop = 14
queen = 10

[shadow]
key_color = [0.05, 0.05, 0.05, 1.0]
fill_color = [0.025, 0.025, 0.025, 1.0]
back_color = [0.025, 0.025, 0.025, 1.0]
amb_color = [0.1, 0.1, 0.15, 1.0]
