[colors]
black = [0.1, 0.1, 0.1, 1.0]
white = [0.9, 0.9, 0.9, 1.0]
grey = [0.2, 0.2, 0.2, 1.0]
sky = [0.3, 0.3, 0.5, 1.0]

[camera]
height = 6.0
distance = 6.0
fov = 0.125

[light]
key_dir = [1.0, -1.5, 2.0, 0.0]
fill_dir = [-1.0, -0.5, 1.0, 0.0]
back_dir = [1.0, -1.5, -2.0, 0.0]
key_color = [0.7, 0.8, 0.9, 1.0]
fill_color = [0.3, 0.3, 0.3, 1.0]
back_color = [0.3, 0.3, 0.3, 1.0]
amb_color = [0.3, 0.3, 0.3, 1.0]
